# Generated by Django 2.2.3 on 2020-10-13 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('issue', models.CharField(max_length=100, verbose_name='Asunto')),
                ('messaje', models.TextField(verbose_name='Mensaje')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
