# Generated by Django 2.2.3 on 2020-10-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
