# Generated by Django 2.2.3 on 2020-11-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201031_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='description',
            name='link',
            field=models.FileField(blank=True, null=True, upload_to='web/files/'),
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='titulo'),
        ),
    ]
