# Generated by Django 2.2.3 on 2020-11-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201103_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='titulo')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(choices=[('AZUL', 'AZUL'), ('CELESTE', 'CELESTE'), ('ROJO', 'ROJO'), ('NARANJA', 'NARANJA')], default='AZUL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(blank=True, max_length=50, null=True, verbose_name='titulo')),
                ('text', models.TextField()),
                ('book', models.CharField(blank=True, max_length=70, null=True, verbose_name='titulo')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
