# Generated by Django 2.2.3 on 2020-11-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_othersites_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othersites',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='is_active',
            new_name='active',
        ),
    ]
