# Generated by Django 2.2.3 on 2020-11-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_suscriptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendSites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='titulo')),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('image_ref', models.ImageField(blank=True, default='image_placeholder.jpg', null=True, upload_to='friendsites/')),
            ],
        ),
    ]
