# Generated by Django 2.2.3 on 2020-12-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201125_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptor',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
    ]
