# Generated by Django 2.2.3 on 2020-12-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_suscriptor_name'),
        ('core', '0011_auto_20201223_1546'),
    ]

    operations = [
    ]
