# Generated by Django 2.2.3 on 2021-01-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201223_1546'),
        ('core', '0011_suscriptor_name'),
    ]

    operations = [
    ]
