# Generated by Django 2.2.3 on 2021-01-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20210104_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song', models.FileField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
