# Generated by Django 2.2.3 on 2021-01-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(upload_to='music/'),
        ),
    ]
