# Generated by Django 2.2.3 on 2021-01-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210104_2347'),
        ('core', '0012_merge_20201226_1914'),
    ]

    operations = [
    ]
