# Generated by Django 2.2.3 on 2021-02-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20210206_0348'),
        ('core', '0014_auto_20210104_2347'),
    ]

    operations = [
    ]
