# Generated by Django 2.2.3 on 2021-02-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20210226_1202'),
        ('core', '0015_merge_20210105_0032'),
    ]

    operations = [
    ]
