# Generated by Django 2.2.3 on 2021-02-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20210228_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscriptor',
            options={'ordering': ['date']},
        ),
    ]
