# Generated by Django 2.2.3 on 2020-10-19 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/images/')),
                ('link', models.FileField(blank=True, null=True, upload_to='books/files/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
