# Generated by Django 2.2.3 on 2020-10-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
