# Generated by Django 2.2.3 on 2020-11-04 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogentry_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
