# Generated by Django 2.2.3 on 2020-11-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
    ]
